### ISSUE TITLE
about the movement of models

### ISSUE THREAD

**Issue by rabiakran** [Gabryxx7/RobotArmHelix#4]
I'm trying to make a project similar to yours, but I want the models to move automatically with the values entered in the textbox. Do you have an opinion or suggestion about this?

**Comment by Gabryxx7** [comment]
I haven't ran this project in years but I remember that being the whole point of the project.
If you enter the values in the textbox and click "Go To position" the model will move to the position.
If you want to trigger the function `StartInverseKinematics` at every keypress, you'll have to change this line: 
https://github.com/Gabryxx7/RobotArmHelix/blob/43f9ff108f28e8eb85c64d4370aa1777c4c5fd6c/RobotArmHelix/MainWindow.xaml#L57

Change `Click="StartInverseKinematics"` to `KeyDown ="StartInverseKinematics"`

You might also have to change the second parameter's type from `RoutedEventArgs` to `KeyEventArgs`:
https://github.com/Gabryxx7/RobotArmHelix/blob/43f9ff108f28e8eb85c64d4370aa1777c4c5fd6c/RobotArmHelix/MainWindow.xaml.cs#L603

See here on how to handle `KeyDown` events:
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/how-to-detect-when-the-enter-key-pressed?view=netframeworkdesktop-4.8
